import { useCallback, useEffect, useMemo, useState } from 'react';
import { ArrowLeft, LocateFixed, MapPin, RefreshCw, Users } from 'lucide-react';
import { loadSharedRepertoire, loadOwnProfile, saveProfile } from '@/lib/cloud';
import type { Profile, Tune } from '@/types';

interface CommunityProps { userId: string; ownTunes: Tune[]; onBack: () => void; }
interface Nearby extends Profile { distance: number; shared: string[]; }

function distanceKm(aLat: number, aLng: number, bLat: number, bLng: number) { const r = 6371; const dLat = (bLat-aLat)*Math.PI/180; const dLng = (bLng-aLng)*Math.PI/180; const a = Math.sin(dLat/2)**2 + Math.cos(aLat*Math.PI/180)*Math.cos(bLat*Math.PI/180)*Math.sin(dLng/2)**2; return r*2*Math.atan2(Math.sqrt(a), Math.sqrt(1-a)); }
function tuneKey(tune: Tune) { return tune.title.trim().toLocaleLowerCase().replace(/[^a-z0-9]+/g, ' '); }

export default function Community({ userId, ownTunes, onBack }: CommunityProps) {
  const [profile, setProfile] = useState<Profile | null>(null);
  const [profiles, setProfiles] = useState<Profile[]>([]);
  const [sharedTunes, setSharedTunes] = useState<Tune[]>([]);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState('');
  const [label, setLabel] = useState('');
  const [sharing, setSharing] = useState(false);
  const [radius, setRadius] = useState(50);

  const refresh = useCallback(async () => { setBusy(true); setMessage(''); try { const [own, shared] = await Promise.all([loadOwnProfile(userId), loadSharedRepertoire()]); setProfile(own); setSharing(own?.sharing_enabled ?? false); setLabel(own?.location_label ?? ''); setProfiles(shared.profiles.filter((p) => p.id !== userId)); setSharedTunes(shared.tunes); } catch { setMessage('Could not load nearby players right now.'); } finally { setBusy(false); } }, [userId]);
  useEffect(() => { void refresh(); }, [refresh]);

  async function enableLocation() { if (!navigator.geolocation) { setMessage('Location is not available in this browser.'); return; } setBusy(true); navigator.geolocation.getCurrentPosition(async (position) => { try { const next = await saveProfile({ display_name: profile?.display_name ?? 'Ethnotes player', sharing_enabled: true, location_label: label || 'Nearby', latitude: Number(position.coords.latitude.toFixed(2)), longitude: Number(position.coords.longitude.toFixed(2)) }); setProfile(next); setSharing(true); await refresh(); } catch { setMessage('Could not save your location.'); setBusy(false); } }, () => { setMessage('Location permission was not granted.'); setBusy(false); }, { enableHighAccuracy: false, maximumAge: 300000, timeout: 10000 }); }
  async function saveSharing(next: boolean) { setBusy(true); try { const saved = await saveProfile({ display_name: profile?.display_name ?? 'Ethnotes player', sharing_enabled: next, location_label: label || null, latitude: profile?.latitude ?? null, longitude: profile?.longitude ?? null }); setProfile(saved); setSharing(next); } catch { setMessage('Could not update sharing preferences.'); } finally { setBusy(false); } }

  const nearby = useMemo<Nearby[]>(() => { if (!profile?.latitude || !profile.longitude) return []; const names = new Map<string, Tune[]>(); sharedTunes.forEach((tune) => { if (!tune.user_id) return; names.set(tune.user_id, [...(names.get(tune.user_id) ?? []), tune]); }); return profiles.filter((other) => other.latitude !== null && other.longitude !== null).map((other) => { const shared = (names.get(other.id) ?? []).filter((tune) => ownTunes.some((mine) => tuneKey(mine) === tuneKey(tune))).map((tune) => tune.title); return { ...other, distance: distanceKm(profile.latitude!, profile.longitude!, other.latitude!, other.longitude!), shared }; }).filter((other) => other.distance <= radius).sort((a, b) => b.shared.length - a.shared.length || a.distance - b.distance); }, [profile, profiles, sharedTunes, ownTunes, radius]);

  return <div className="mx-auto max-w-4xl px-4 py-8 sm:px-6 lg:px-8"><button onClick={onBack} className="mb-6 inline-flex items-center gap-2 rounded-lg px-3 py-2 text-sm font-medium text-wood-600 hover:bg-wood-100 dark:text-parchment-200 dark:hover:bg-wood-800"><ArrowLeft className="h-4 w-4" />Back to library</button><div className="mb-7"><h1 className="font-display text-3xl font-semibold text-wood-800 dark:text-parchment-100">Tunes around me</h1><p className="mt-2 text-wood-500 dark:text-parchment-200/70">Find nearby musicians who opted in to compare repertoires. Your exact location is never stored.</p></div>
    <div className="mb-6 rounded-2xl border border-wood-200 bg-parchment-50 p-5 dark:border-wood-700 dark:bg-wood-900"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="font-display text-xl font-semibold text-wood-800 dark:text-parchment-100">Share your repertoire</h2><p className="mt-1 max-w-xl text-sm text-wood-500 dark:text-parchment-200/70">Only an approximate location and tune titles are used for matching. Turn this off any time.</p></div><button disabled={busy} onClick={() => sharing ? void saveSharing(false) : void enableLocation()} className={`rounded-lg px-4 py-2 text-sm font-semibold ${sharing ? 'border border-wood-300 text-wood-700 dark:border-wood-600 dark:text-parchment-100' : 'bg-amber-700 text-white hover:bg-amber-800'}`}>{sharing ? 'Stop sharing' : 'Share my location'}</button></div>{sharing && <div className="mt-4 flex items-center gap-2 text-sm text-green-700 dark:text-green-300"><LocateFixed className="h-4 w-4" />Sharing approximate location{label && ` as ${label}`}</div>}{message && <p className="mt-3 text-sm text-red-700 dark:text-red-300">{message}</p>}</div>
    <div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2 text-sm text-wood-600 dark:text-parchment-200"><Users className="h-4 w-4" />{nearby.length} nearby players found</div><div className="flex items-center gap-2"><label className="text-xs text-wood-500 dark:text-parchment-200/70">Within</label><select value={radius} onChange={(e) => setRadius(Number(e.target.value))} className="rounded-lg border border-wood-200 bg-parchment-50 px-2 py-1.5 text-sm dark:border-wood-700 dark:bg-wood-900"><option value="10">10 km</option><option value="50">50 km</option><option value="100">100 km</option><option value="500">500 km</option></select><button onClick={() => void refresh()} className="rounded-lg p-2 text-wood-500 hover:bg-wood-100 dark:text-parchment-200 dark:hover:bg-wood-800" aria-label="Refresh"><RefreshCw className={`h-4 w-4 ${busy ? 'animate-spin' : ''}`} /></button></div></div>
    {!sharing ? <div className="rounded-2xl border border-dashed border-wood-300 px-6 py-16 text-center dark:border-wood-700"><MapPin className="mx-auto mb-3 h-8 w-8 text-amber-600" /><p className="font-display text-xl font-semibold text-wood-800 dark:text-parchment-100">Choose to be discoverable</p><p className="mx-auto mt-2 max-w-md text-sm text-wood-500 dark:text-parchment-200/70">Share an approximate location to see musicians near you and compare common tunes.</p></div> : nearby.length === 0 ? <div className="rounded-2xl border border-dashed border-wood-300 px-6 py-16 text-center dark:border-wood-700"><Users className="mx-auto mb-3 h-8 w-8 text-amber-600" /><p className="font-display text-xl font-semibold text-wood-800 dark:text-parchment-100">No nearby matches yet</p><p className="mt-2 text-sm text-wood-500 dark:text-parchment-200/70">Invite fellow players to create an Ethnotes account and opt into sharing.</p></div> : <div className="space-y-3">{nearby.map((person) => <div key={person.id} className="rounded-2xl border border-wood-200 bg-parchment-50 p-5 dark:border-wood-700 dark:bg-wood-900"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-display text-xl font-semibold text-wood-800 dark:text-parchment-100">{person.display_name}</h3><p className="mt-1 flex items-center gap-1.5 text-sm text-wood-500 dark:text-parchment-200/70"><MapPin className="h-3.5 w-3.5" />{person.location_label || 'Nearby'} · {person.distance.toFixed(1)} km away</p></div><span className="rounded-full bg-amber-100 px-3 py-1 text-sm font-semibold text-amber-800 dark:bg-amber-900/40 dark:text-amber-200">{person.shared.length} shared {person.shared.length === 1 ? 'tune' : 'tunes'}</span></div>{person.shared.length > 0 && <p className="mt-4 border-t border-wood-100 pt-3 text-sm text-wood-600 dark:border-wood-800 dark:text-parchment-200/80">{person.shared.slice(0, 6).join(' · ')}{person.shared.length > 6 ? ' …' : ''}</p>}</div>)}</div>}</div>;
}
